FROM openjdk:8-jre-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz && \
    tar -xvf spark-3.1.1-bin-hadoop3.2.tgz && \
    mv spark-3.1.1-bin-hadoop3.2 /spark && \
    rm spark-3.1.1-bin-hadoop3.2.tgz

ENV SPARK_HOME=/spark

CMD ["/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]